### ISSUE TITLE
Hello,can I ask you a few questions about Annabot?

### ISSUE THREAD

**Issue by zhangyue-se** [IanDarwin/annabot#1]
Hello, I'm trying to run your Annabot in IDEA now, but I'm running into a few problems. First of all what is his parameter input? I am currently typing JPA's *Claim. Java. Class file, but the following error occurs at runtime. How can I run it correctly?

Error:
    Connected to the target VM, address: '127.0.0.1:60476', transport: 'socket'
    6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments
    信息: parseArg: i=0: arg javaclaims/jpaclass
    6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt
    信息: optind=0, argv.length=2
    6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments
    信息: parseArg: i=1: arg systests
    6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt
    信息: optind=0, argv.length=2
    SourceUtils.doDir(): javaclaims/jpaclass
    SourceUtils.doDir(): javaclaims/jpaclass/JPAEntityHasIdClaim.class
    Exception in thread "main" java.lang.NoClassDefFoundError: jpa/JPAEntityHasIdClaim (wrong name: JPAEntityHasIdClaim)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.darwinsys.io.ClassSourceUtils.doFile(ClassSourceUtils.java:180)
	at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:153)
	at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:165)
	at com.darwinsys.io.ClassSourceUtils.startDir(ClassSourceUtils.java:136)
	at com.darwinsys.io.ClassSourceUtils.classListFromDirectory(ClassSourceUtils.java:118)
	at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:48)
	at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:56)
	at annabot.AnnaBot.main(AnnaBot.java:75)

**Comment by IanDarwin** [comment]
Thanks for your interest.

I haven't done anything with Annabot in years. I will take a look later today or in the morning
and see if I can make it work on IntelliJ. It may need updating for Gradle.

**Comment by zhangyue-se** [comment]
OK, thank you very much for replying to me in your busy schedule.

**Comment by IanDarwin** [comment]
On Thu, Jun 03, 2021 at 06:22:32AM -0700, Yue Zhang wrote:
> Hello, I'm trying to run your Annabot in IDEA now, but I'm running into a few problems. First of all what is his parameter input? I am currently typing JPA's *Claim. Java. Class file, but the following error occurs at runtime. How can I run it correctly?

I found a bit of time to work on Annabot. The project was so old that the tooling
did not work. I have updated the pom.xml and done minor other cleanups so that you
can now build it with Maven, and I got as far as being able to build a single
Jar file with everything. That has all been pushed to the github repo.

So you can now do
	cd annabot
	git pull
	mvn clean test package assembly:single

I didn't get as far as trying it in IntelliJ, buth the error
java.lang.NoClassDefFoundError: jpa/JPAEntityHasIdClaim (wrong name: JPAEntityHasIdClaim)
implies that the classpath is being set incorrectly. Maybe that clue will help you
find the problem, and if not, I will try running the current version myself under Idea
and see if I can figure it out. The file that is apparently triggering the issue is
com.darwinsys.io.ClassSourceUtils, which is in github.com/IanDarwin/darwinsys-api
if you care to work through the issue.


> Error:
>     Connected to the target VM, address: '127.0.0.1:60476', transport: 'socket'
>     6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments
>     信息: parseArg: i=0: arg javaclaims/jpaclass
>     6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt
>     信息: optind=0, argv.length=2
>     6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments
>     信息: parseArg: i=1: arg systests
>     6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt
>     信息: optind=0, argv.length=2
>     SourceUtils.doDir(): javaclaims/jpaclass
>     SourceUtils.doDir(): javaclaims/jpaclass/JPAEntityHasIdClaim.class
>     Exception in thread "main" java.lang.NoClassDefFoundError: jpa/JPAEntityHasIdClaim (wrong name: JPAEntityHasIdClaim)
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
> 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
> 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at com.darwinsys.io.ClassSourceUtils.doFile(ClassSourceUtils.java:180)
> 	at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:153)
> 	at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:165)
> 	at com.darwinsys.io.ClassSourceUtils.startDir(ClassSourceUtils.java:136)
> 	at com.darwinsys.io.ClassSourceUtils.classListFromDirectory(ClassSourceUtils.java:118)
> 	at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:48)
> 	at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:56)
> 	at annabot.AnnaBot.main(AnnaBot.java:75)

**Comment by zhangyue-se** [comment]
> On Thu, Jun 03, 2021 at 06:22:32AM -0700, Yue Zhang wrote: Hello, I'm trying to run your Annabot in IDEA now, but I'm running into a few problems. First of all what is his parameter input? I am currently typing JPA's *Claim. Java. Class file, but the following error occurs at runtime. How can I run it correctly?
> I found a bit of time to work on Annabot. The project was so old that the tooling did not work. I have updated the pom.xml and done minor other cleanups so that you can now build it with Maven, and I got as far as being able to build a single Jar file with everything. That has all been pushed to the github repo. So you can now do cd annabot git pull mvn clean test package assembly:single I didn't get as far as trying it in IntelliJ, buth the error java.lang.NoClassDefFoundError: jpa/JPAEntityHasIdClaim (wrong name: JPAEntityHasIdClaim) implies that the classpath is being set incorrectly. Maybe that clue will help you find the problem, and if not, I will try running the current version myself under Idea and see if I can figure it out. The file that is apparently triggering the issue is com.darwinsys.io.ClassSourceUtils, which is in github.com/IanDarwin/darwinsys-api if you care to work through the issue.
> […](#)
> Error: Connected to the target VM, address: '127.0.0.1:60476', transport: 'socket' 6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments 信息: parseArg: i=0: arg javaclaims/jpaclass 6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt 信息: optind=0, argv.length=2 6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt parseArguments 信息: parseArg: i=1: arg systests 6月 03, 2021 9:14:24 下午 com.darwinsys.lang.GetOpt getopt 信息: optind=0, argv.length=2 SourceUtils.doDir(): javaclaims/jpaclass SourceUtils.doDir(): javaclaims/jpaclass/JPAEntityHasIdClaim.class Exception in thread "main" java.lang.NoClassDefFoundError: jpa/JPAEntityHasIdClaim (wrong name: JPAEntityHasIdClaim) at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) at com.darwinsys.io.ClassSourceUtils.doFile(ClassSourceUtils.java:180) at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:153) at com.darwinsys.io.ClassSourceUtils.doDir(ClassSourceUtils.java:165) at com.darwinsys.io.ClassSourceUtils.startDir(ClassSourceUtils.java:136) at com.darwinsys.io.ClassSourceUtils.classListFromDirectory(ClassSourceUtils.java:118) at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:48) at com.darwinsys.io.ClassSourceUtils.classListFromSource(ClassSourceUtils.java:56) at annabot.AnnaBot.main(AnnaBot.java:75)

OK, thank you for taking time out of your busy schedule to answer my questions! I've been looking at your code these days, trying to get it to run again.
